from fastapi import FastAPI, APIRouter, HTTPException
from dotenv import load_dotenv
from starlette.middleware.cors import CORSMiddleware
from motor.motor_asyncio import AsyncIOMotorClient
import os
import logging
import uuid
import base64
from pathlib import Path
from pydantic import BaseModel, Field
from typing import Optional

from emergentintegrations.llm.chat import LlmChat, UserMessage, ImageContent


ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / ".env")

mongo_url = os.environ["MONGO_URL"]
client = AsyncIOMotorClient(mongo_url)
db = client[os.environ["DB_NAME"]]

EMERGENT_LLM_KEY = os.environ["EMERGENT_LLM_KEY"]
GEMINI_IMAGE_MODEL = "gemini-3.1-flash-image-preview"

app = FastAPI()
api_router = APIRouter(prefix="/api")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


class GenerateBabyRequest(BaseModel):
    father_image_base64: str = Field(..., description="Base64 encoded image of father (male parent)")
    mother_image_base64: str = Field(..., description="Base64 encoded image of mother (female parent)")
    gender: str = Field(default="random", description="'male' | 'female' | 'random'")


class GenerateBabyResponse(BaseModel):
    image_base64: str
    mime_type: str


def _strip_data_url(b64: str) -> str:
    if "," in b64 and b64.strip().startswith("data:"):
        return b64.split(",", 1)[1]
    return b64


def _build_prompt(gender: str) -> str:
    if gender == "male":
        child_desc = "a young boy"
        pronoun = "his"
    elif gender == "female":
        child_desc = "a young girl"
        pronoun = "her"
    else:
        child_desc = "a young child"
        pronoun = "their"

    return (
        f"You are given two portrait photos: the first image is the FATHER and the second image is the MOTHER. "
        f"Create ONE highly photorealistic portrait of {child_desc} aged between 2 and 5 years old, "
        f"who is the biological child of these two parents. "
        f"The child's face MUST realistically blend genetic features from BOTH parents, respecting real-world genetic probabilities: "
        f"blend skin tone as a natural mix of both parents' skin tones; "
        f"eye color should follow real genetic dominance (brown is dominant over blue/green, so if one parent has brown eyes the child likely has brown eyes); "
        f"hair color and texture should be a natural genetic mix (darker hair generally dominant); "
        f"face shape, nose, lips, chin, eyebrows and cheekbones should be a plausible mixture of both parents' features; "
        f"ethnic features must be a realistic blend of the two parents. "
        f"The child should look natural, adorable and believable, as if photographed in real life. "
        f"Style: high-resolution studio photograph, soft natural lighting, plain neutral pastel background, sharp focus on {pronoun} face, "
        f"child smiling gently, head-and-shoulders framing, no text, no watermark, no filters. "
        f"Output only the child, not the parents."
    )


@api_router.get("/")
async def root():
    return {"message": "BabyMix API up"}


@api_router.post("/generate-baby", response_model=GenerateBabyResponse)
async def generate_baby(payload: GenerateBabyRequest):
    gender = payload.gender.lower().strip()
    if gender not in ("male", "female", "random"):
        gender = "random"

    father_b64 = _strip_data_url(payload.father_image_base64)
    mother_b64 = _strip_data_url(payload.mother_image_base64)

    if not father_b64 or not mother_b64:
        raise HTTPException(status_code=400, detail="Both parent images are required")

    try:
        base64.b64decode(father_b64, validate=True)
        base64.b64decode(mother_b64, validate=True)
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid base64 image data")

    prompt = _build_prompt(gender)
    session_id = str(uuid.uuid4())

    try:
        chat = LlmChat(
            api_key=EMERGENT_LLM_KEY,
            session_id=session_id,
            system_message="You are a photorealistic portrait generator that combines two parent photos into a believable child portrait.",
        )
        chat.with_model("gemini", GEMINI_IMAGE_MODEL).with_params(modalities=["image", "text"])

        msg = UserMessage(
            text=prompt,
            file_contents=[ImageContent(father_b64), ImageContent(mother_b64)],
        )

        text, images = await chat.send_message_multimodal_response(msg)
        logger.info("Gemini text response length=%s images=%s", len(text or ""), len(images or []))

        if not images:
            raise HTTPException(status_code=502, detail="No image generated by the model")

        img = images[0]
        return GenerateBabyResponse(image_base64=img["data"], mime_type=img.get("mime_type", "image/png"))
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("Baby generation failed")
        raise HTTPException(status_code=500, detail=f"Generation failed: {str(e)}")


app.include_router(api_router)

app.add_middleware(
    CORSMiddleware,
    allow_credentials=True,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.on_event("shutdown")
async def shutdown_db_client():
    client.close()
